### PR TITLE
Update docs/static-library.md

### PR DESCRIPTION
**Pull request by BruegelN**
I'm not sure about the embree part, because I don't use embree personaly.
However I think it's not relevenat anymore. Embree always compiles as static lib when `LIBIGL_WITH_EMBREE` is set to true: https://github.com/libigl/libigl/blob/master/cmake/libigl.cmake#L269-L295

Shoudn't the __Extra__ section better be integrated into [External Dependencies](https://libigl.github.io/third-party/ )?

What about the __Compressed .h/.cpp pair__ part? This is outdated an can be deleted, right?

Just let me know what you think such that I can update this PR accordingly.

### CODE REVIEW

**Comment by jdumas** [comment]
Yeah this page definitely needs an update!

Some comments:
- You may want to use [Admonition-style](https://squidfunk.github.io/mkdocs-material/extensions/admonition/) blocks for more visible warnings.
- Maybe add a `tip` block that if you set the `LIBIGL_USE_STATIC_LIBRARY` in the CMake directly, you need to delete or update your `CMakeCache.txt` for it to be taken into account.
- "Installing Embree 2.0" can go away I think.
- "Extra" should definitely go into "External dependencies" (and be updated accordingly).
- I think the part about the compressed headers can go away (@alecjacobson ?)
- The part mentioning `autoexplicit.sh` can be updated to point to [this separate repo](https://github.com/libigl/libigl-scripts) which contains said script. (Although I wonder if anyone has used it recently? I usually do it by hand).
- The "Optional" section should also be integrated into the "External Dependency" page.
- I need to double-check, but I think a better way to install libigl now is to type `make install` and set the `CMAKE_INSTALL_PREFIX` to set the destination folder where to install libigl (this would also export the `igl::core` target in a cmake config file).

**Comment by jdumas** [comment]
Hmm so if I type `make install` it will indeed correctly install libigl into the right folder, but it will also install embree, even though we don't really support installing the `igl::embree` module at the moment. This is annoying, because there is no way to avoid Embree's CMake calling the `install()` on its own targets. However, it looks like add the `EXCLUDE_FROM_ALL` option to the line
```cmake
add_subdirectory("${EMBREE_DIR}" "embree" EXCLUDE_FROM_ALL)
```
in `libigl.cmake` does the trick, and `make install` will only install the main libigl target!

**Comment by BruegelN** [comment]
Thank you for your detailed feedback @jdumas!
I've included most of the changes proposed by you.

The "External Dependencies" page definitely needs a rework as well! But I don't want to include it into this PR to keep the scope somewhat limited and I'm not very experienced with most the external libs.
But I'll add a second PR later for the page about the _libigl example project_

Regarding installation with `make install` to `CMAKE_INSTALL_PREFIX`:
Do you want me to added ad PR to the main libigl-repo with your fix? I could test it on macOS and a Ubuntu machine beforehand. Or just leave it for now?

______

@alecjacobson I've deleted a few section which looked outdated to me:
- "Installing Embree 2.0" -> has nothing to do with static library compilation. However the section in about embree on the "External Dependencies" pages needs to be updated.
- "compressed headers" or is there a reason to keep this?
- AntTweakBar

**Comment by jdumas** [comment]
Awesome, thanks! Yes maybe you could also create a PR to add the `EXCLUDE_FROM_ALL` in the libigl repo, so we can update the doc accordingly.

**Comment by jdumas** [comment]
Merged! Sorry it took a while. Appreciate your effort in improving libigl :D

**Pull request merged**
