### PR TITLE
Update docs/example-project.md

### PR DESCRIPTION
**Pull request by BruegelN**
* Added info on how cmake looks for libigl when building libigl-example-project. Is this detailed enough?
* Added screenshot of example_bin.

Please let me know, what you think.
Should I include a link to static-library.md with a hint about compile times?

_____
By the way I've noticed that libigl-example-project recommends to [clone libigl recursive](https://github.com/libigl/libigl-example-project/blob/master/cmake/FindLIBIGL.cmake#L31), which is not required anymore.

### CODE REVIEW

**Comment by jdumas** [comment]
Thanks! I've updated the text a little bit. But you're not really supposed to pass `LIBIGL_INCLUDE_DIR` to CMake to specify the libigl root directory. Right now the only way to set the libigl root directory is by setting an environment variable, but this can be annoying on Windows. We should modify the `FindLIBIGL.cmake` in the example project to also look up the `CMake` variable `LIBIGL_DIR` so it can be passed on directly via the command-line.

**Comment by BruegelN** [comment]
Thank you for the improvement!

Regarding `LIBIGL_INCLUDE_DIR`:
Currently `find_path()` is used inside [FindLIBIGL.cmake](https://github.com/libigl/libigl-example-project/blob/master/cmake/FindLIBIGL.cmake#L10)
While I personaly think an older version of the `find_path` documentation more clear on the topic: https://cmake.org/cmake/help/v3.0/command/find_path.html also the latest version of the `find_path` states that one can pass `-DVAR=value` via the command line (https://cmake.org/cmake/help/latest/command/find_path.html see 2.)
Maybe I didn't get your point but calling 
```bash
cmake ../ -DLIBIGL_INCLUDE_DIR=~/foo/libigl/include/
```
worked for me so far. Also set or changing `LIBIGL_INCLUDE_DIR` via cmake-gui worked for me.

But to be honest one thing that's quite confusing: if using an ENV you have to specify the root of libigl (\~/foo/libigl/) where as  `LIBIGL_INCLUDE_DIR` will point to the include dir (\~/foo/libigl/__include/__)

**Comment by jdumas** [comment]
The fact that this work is not because `find_path()` uses the `-DVAR=value` option in 2. of the documentation (this doesn't refer to the same `VAR` used to store the result of the `find_path()` command). This works because `find_path()` stores the result in a [*cache* variable](https://cliutils.gitlab.io/modern-cmake/chapters/basics/variables.html). But anyway the fact that it works this way is not intentional, and as you say having to specify the root of the lbigl installation with the `ENV` variable `LIBIGL_DIR`, but having to specify the include directory if you want to pass `-DLIBIGL_INCLUDE=...` to the CMake command line is quite confusing.

What I am suggesting is to simply modify the `FindLIBIGL.cmake` as follows:
```cmake
# - Try to find the LIBIGL library
# Once done this will define
#
#  LIBIGL_FOUND - system has LIBIGL
#  LIBIGL_INCLUDE_DIR - **the** LIBIGL include directory
if(LIBIGL_FOUND)
    return()
endif()

find_path(LIBIGL_INCLUDE_DIR igl/readOBJ.h
    HINTS
        ENV LIBIGL_DIR
        LIBIGL_DIR
    PATHS
        ${CMAKE_SOURCE_DIR}/../..
        ${CMAKE_SOURCE_DIR}/..
        ${CMAKE_SOURCE_DIR}
        ${CMAKE_SOURCE_DIR}/libigl
        ${CMAKE_SOURCE_DIR}/../libigl
        ${CMAKE_SOURCE_DIR}/../../libigl
        /usr
        /usr/local
        /usr/local/igl/libigl
    PATH_SUFFIXES include
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(LIBIGL
    "\nlibigl not found --- You can download it using:\n\tgit clone --recursive https://github.com/libigl/libigl.git ${CMAKE_SOURCE_DIR}/../libigl"
    LIBIGL_INCLUDE_DIR)
mark_as_advanced(LIBIGL_INCLUDE_DIR)

list(APPEND CMAKE_MODULE_PATH "${LIBIGL_INCLUDE_DIR}/../cmake")
include(libigl)
```

Then you will be able to set the root directory `LIBIGL_DIR` by either passing it as a command-line argument, or as an environment variable.

**Comment by jdumas** [comment]
@alecjacobson @danielepanozzo can I get write capabilities on the example-project repository so I can implement this suggested change to our `FindLIBIGL.cmake`?

**Comment by BruegelN** [comment]
Hi @jdumas thank you for you suggestion! I forgot to reply to you, sorry for that :/
I've started to implement your suggestion but hadn't have time to fully test it (https://github.com/BruegelN/libigl-example-project/tree/rework-FindLIBIGL.cmake) do you want me to submit a PR on the `libigl-example-project` repo so we can continue to talk about this over there? Later on we can update the documentation accordingly.

**Comment by jdumas** [comment]
I don't have merge capabilities on the libigl-example-project for now, but in the meantime feel free to submit a PR with those changes yes.

**Pull request merged**
